/* EDITE APENAS ESTA LISTA PARA TROCAR CARGOS, TEXTOS E FOTOS */
const membros=[
{nome:'Baby',cargo:'Membro da Família Cuba',imagem:'images/baby.png',descricao:'Descrição provisória. Troque este texto pela função e pela história deste integrante.',frase:'Lealdade se prova em silêncio.'},
{nome:'Caio',cargo:'Membro da Família Cuba',imagem:'images/caio.png',descricao:'Descrição provisória. Troque este texto pela função e pela história deste integrante.',frase:'Respeito é conquistado.'},
{nome:'Caroll',cargo:'Membro da Família Cuba',imagem:'images/caroll.png',descricao:'Descrição provisória. Troque este texto pela função e pela história deste integrante.',frase:'Família é escolha.'},
{nome:'DuFlair',cargo:'Membro da Família Cuba',imagem:'images/duflair.png',descricao:'Descrição provisória. Troque este texto pela função e pela história deste integrante.',frase:'Quem permanece, constrói.'},
{nome:'Nickolay',cargo:'Membro da Família Cuba',imagem:'images/nickolay.png',descricao:'Descrição provisória. Troque este texto pela função e pela história deste integrante.',frase:'A palavra tem peso.'},
{nome:'Raissa',cargo:'Membro da Família Cuba',imagem:'images/raissa.png',descricao:'Descrição provisória. Troque este texto pela função e pela história deste integrante.',frase:'Silêncio também mata.'},
{nome:'Renan',cargo:'Membro da Família Cuba',imagem:'images/renan.png',descricao:'Descrição provisória. Troque este texto pela função e pela história deste integrante.',frase:'Lealdade acima de tudo.'},
{nome:'Xaulin',cargo:'Membro da Família Cuba',imagem:'images/xaulin.png',descricao:'Descrição provisória. Troque este texto pela função e pela história deste integrante.',frase:'Respeito abre portas.'}
];
const mensagens=['Inicializando sistema...','Verificando credenciais...','Descriptografando arquivos...','Validando identidade...','Acesso autorizado.'];
const intro=['Se você está lendo isso...','significa que alguém acreditou no seu potencial.','Durante esta missão, você foi observado.','Cada decisão foi analisada.','Cada palavra teve importância.','Agora é hora de conhecer quem realmente somos.'];
const loader=document.getElementById('loader'),site=document.getElementById('site'),loaderText=document.getElementById('loaderText'),bar=document.getElementById('progressBar'),enter=document.getElementById('enterButton'),cont=document.getElementById('continueButton'),type=document.getElementById('typewriter'),music=document.getElementById('themeMusic'),grid=document.getElementById('membersGrid'),modal=document.getElementById('memberModal');
let i=0;const load=setInterval(()=>{loaderText.textContent=mensagens[i];bar.style.width=((i+1)/mensagens.length*100)+'%';i++;if(i===mensagens.length){clearInterval(load);setTimeout(()=>{loader.style.opacity='0';loader.style.transition='.8s';setTimeout(()=>{loader.remove();site.classList.remove('hidden');observe()},800)},700)}},850);
function typeIntro(){let l=0,c=0;type.textContent='';function next(){if(l>=intro.length){cont.classList.remove('hidden');return}if(c<intro[l].length){type.textContent+=intro[l][c++];setTimeout(next,38)}else{type.textContent+='\n\n';l++;c=0;setTimeout(next,450)}}next()}
enter.onclick=async()=>{try{music.volume=.28;await music.play()}catch(e){}document.getElementById('intro').scrollIntoView({behavior:'smooth'});if(!type.dataset.started){type.dataset.started='1';typeIntro()}};cont.onclick=()=>document.getElementById('quem-somos').scrollIntoView({behavior:'smooth'});
function render(){grid.innerHTML='';membros.forEach((m,idx)=>{const el=document.createElement('article');el.className='member reveal';el.innerHTML=`<img src="${m.imagem}" alt="${m.nome}"><div><span>${m.cargo}</span><h3>${m.nome}</h3></div>`;el.onclick=()=>openMember(idx);grid.appendChild(el)})}function openMember(idx){const m=membros[idx];document.getElementById('modalImage').src=m.imagem;document.getElementById('modalName').textContent=m.nome;document.getElementById('modalRole').textContent=m.cargo;document.getElementById('modalDescription').textContent=m.descricao;document.getElementById('modalQuote').textContent='“'+m.frase+'”';modal.classList.remove('hidden')}document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal.classList.add('hidden'));document.addEventListener('keydown',e=>{if(e.key==='Escape')modal.classList.add('hidden')});function observe(){const o=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.13});document.querySelectorAll('.reveal').forEach(x=>o.observe(x))}render();
