-- CUBA Mercadinho — separação dos estoques entre Baú da Gerência e Baú do QG
-- Execute UMA VEZ no SQL Editor do Supabase do projeto do Mercadinho.
-- O saldo único atual é preservado como saldo inicial do QG; o Baú da Gerência começa em 0.
-- Não apaga itens, acessos, imagens nem o histórico antigo.

begin;

alter table public.mercado_itens
  add column if not exists estoque_gerencia integer,
  add column if not exists estoque_qg integer;

-- Na primeira execução, migra o saldo antigo (visível aos membros) para o QG.
update public.mercado_itens
set estoque_qg = coalesce(estoque, 0)
where estoque_qg is null;

update public.mercado_itens
set estoque_gerencia = 0
where estoque_gerencia is null;

alter table public.mercado_itens
  alter column estoque_gerencia set default 0,
  alter column estoque_gerencia set not null,
  alter column estoque_qg set default 0,
  alter column estoque_qg set not null;

-- Mantém o campo antigo estoque sincronizado com o QG para compatibilidade.
create or replace function public._mercado_sync_estoque_qg_legacy()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $fn$
begin
  if tg_op = 'INSERT' then
    -- Compatibilidade com inserções antigas que ainda enviam apenas estoque.
    if new.estoque_qg is null or (new.estoque_qg = 0 and coalesce(new.estoque, 0) > 0) then
      new.estoque_qg := coalesce(new.estoque, 0);
    end if;
    new.estoque_gerencia := coalesce(new.estoque_gerencia, 0);
    new.estoque := new.estoque_qg;
    return new;
  end if;

  -- Se uma função antiga alterar estoque, trata o valor como QG.
  if new.estoque is distinct from old.estoque
     and new.estoque_qg is not distinct from old.estoque_qg then
    new.estoque_qg := new.estoque;
  -- Se uma função nova alterar o QG, espelha no campo antigo.
  elsif new.estoque_qg is distinct from old.estoque_qg then
    new.estoque := new.estoque_qg;
  end if;
  return new;
end
$fn$;

drop trigger if exists mercado_sync_estoque_qg_legacy on public.mercado_itens;
create trigger mercado_sync_estoque_qg_legacy
before insert or update of estoque, estoque_qg, estoque_gerencia
on public.mercado_itens
for each row execute function public._mercado_sync_estoque_qg_legacy();

-- Histórico novo e separado: não depende do formato legado de mercado_movimentos.
create table if not exists public.mercado_movimentos_baus (
  id bigint generated by default as identity primary key,
  item_id uuid not null references public.mercado_itens(id) on delete restrict,
  bau text not null check (bau in ('gerencia', 'qg')),
  tipo text not null check (tipo in ('entrada', 'saida', 'ajuste')),
  quantidade integer not null check (quantidade > 0),
  estoque_anterior integer not null check (estoque_anterior >= 0),
  estoque_posterior integer not null check (estoque_posterior >= 0),
  responsavel_nome text not null,
  responsavel_tipo text not null check (responsavel_tipo in ('gerencia', 'membro')),
  responsavel_auth_id uuid,
  responsavel_acesso_id uuid,
  observacao text,
  created_at timestamptz not null default now()
);

create index if not exists mercado_movimentos_baus_data_idx
  on public.mercado_movimentos_baus(created_at desc);
create index if not exists mercado_movimentos_baus_item_idx
  on public.mercado_movimentos_baus(item_id, created_at desc);

alter table public.mercado_movimentos_baus enable row level security;
revoke all on public.mercado_movimentos_baus from anon, authenticated;

-- Os membros e a vitrine do Mercado recebem somente o saldo do QG.
create or replace function public.mercado_listar_itens(p_token text default null)
returns table(id uuid, nome text, descricao text, estoque integer, disponivel boolean)
language plpgsql
security definer
set search_path = public, auth, extensions, pg_temp
as $fn$
declare v record;
begin
  if auth.uid() is not null and coalesce(public.cuba_access_ok(), false) then
    null;
  else
    select * into v from public._mercado_sessao_membro(p_token);
    if v.acesso_id is null then
      raise exception 'Sessão inválida.' using errcode = '28000';
    end if;
  end if;

  return query
    select i.id, i.nome, i.descricao, i.estoque_qg, (i.estoque_qg > 0)
    from public.mercado_itens i
    where i.ativo
    order by i.nome;
end
$fn$;

-- RPC administrativa nova, com dois saldos independentes.
drop function if exists public.mercado_admin_listar_itens_baus();
create function public.mercado_admin_listar_itens_baus()
returns table(
  id uuid, nome text, descricao text,
  estoque_gerencia integer, estoque_qg integer, estoque integer, ativo boolean
)
language plpgsql
security definer
set search_path = public, auth, extensions, pg_temp
as $fn$
begin
  perform public._mercado_exigir_gerencia();
  return query
    select i.id, i.nome, i.descricao, i.estoque_gerencia, i.estoque_qg, i.estoque_qg, i.ativo
    from public.mercado_itens i
    where i.ativo
    order by i.nome;
end
$fn$;

-- Cadastro de item com saldo inicial informado para cada baú.
drop function if exists public.mercado_admin_criar_item_baus(text, text, integer, integer);
create function public.mercado_admin_criar_item_baus(
  p_nome text, p_descricao text, p_estoque_gerencia integer, p_estoque_qg integer
)
returns uuid
language plpgsql
security definer
set search_path = public, auth, extensions, pg_temp
as $fn$
declare v_id uuid;
begin
  perform public._mercado_exigir_gerencia();
  if length(trim(coalesce(p_nome, ''))) = 0 then
    raise exception 'Informe o nome do item.';
  end if;
  if coalesce(p_estoque_gerencia, -1) < 0 or coalesce(p_estoque_qg, -1) < 0 then
    raise exception 'As quantidades não podem ser negativas.';
  end if;

  insert into public.mercado_itens(
    nome, descricao, estoque, estoque_gerencia, estoque_qg, created_by
  )
  values(
    trim(p_nome), nullif(trim(coalesce(p_descricao, '')), ''),
    p_estoque_qg, p_estoque_gerencia, p_estoque_qg, auth.uid()
  )
  returning id into v_id;

  if p_estoque_gerencia > 0 then
    insert into public.mercado_movimentos_baus(
      item_id,bau,tipo,quantidade,estoque_anterior,estoque_posterior,
      responsavel_nome,responsavel_tipo,responsavel_auth_id,observacao
    )
    select v_id,'gerencia','entrada',p_estoque_gerencia,0,p_estoque_gerencia,
      coalesce(p.nome,'Gerência'),'gerencia',auth.uid(),'Saldo inicial do item'
    from (select 1) seed left join public.profiles p on p.user_id=auth.uid();
  end if;

  if p_estoque_qg > 0 then
    insert into public.mercado_movimentos_baus(
      item_id,bau,tipo,quantidade,estoque_anterior,estoque_posterior,
      responsavel_nome,responsavel_tipo,responsavel_auth_id,observacao
    )
    select v_id,'qg','entrada',p_estoque_qg,0,p_estoque_qg,
      coalesce(p.nome,'Gerência'),'gerencia',auth.uid(),'Saldo inicial do item'
    from (select 1) seed left join public.profiles p on p.user_id=auth.uid();
  end if;

  return v_id;
end
$fn$;

-- Entrada ou ajuste de quantidade no baú escolhido pela gerência.
drop function if exists public.mercado_admin_atualizar_bau(uuid, text, text, integer, text);
create function public.mercado_admin_atualizar_bau(
  p_item_id uuid, p_bau text, p_operacao text, p_quantidade integer, p_observacao text default null
)
returns integer
language plpgsql
security definer
set search_path = public, auth, extensions, pg_temp
as $fn$
declare
  v_before integer;
  v_after integer;
  v_nome text;
  v_tipo text;
begin
  perform public._mercado_exigir_gerencia();
  if p_bau not in ('gerencia','qg') then raise exception 'Baú inválido.'; end if;
  if p_operacao not in ('entrada','ajuste') then raise exception 'Operação inválida.'; end if;
  if coalesce(p_quantidade,-1) < 0 or (p_operacao='entrada' and p_quantidade=0) then
    raise exception 'Informe uma quantidade válida.';
  end if;

  if p_bau='gerencia' then
    select i.estoque_gerencia into v_before from public.mercado_itens i
      where i.id=p_item_id and i.ativo for update;
  else
    select i.estoque_qg into v_before from public.mercado_itens i
      where i.id=p_item_id and i.ativo for update;
  end if;
  if not found then raise exception 'Item não encontrado.'; end if;

  v_after := case when p_operacao='entrada' then v_before+p_quantidade else p_quantidade end;
  if v_after=v_before then return v_before; end if;

  if p_bau='gerencia' then
    update public.mercado_itens set estoque_gerencia=v_after where id=p_item_id;
  else
    update public.mercado_itens set estoque_qg=v_after where id=p_item_id;
  end if;

  select p.nome into v_nome from public.profiles p where p.user_id=auth.uid();
  v_tipo := case when p_operacao='ajuste' then 'ajuste' else 'entrada' end;
  insert into public.mercado_movimentos_baus(
    item_id,bau,tipo,quantidade,estoque_anterior,estoque_posterior,
    responsavel_nome,responsavel_tipo,responsavel_auth_id,observacao
  )
  values(
    p_item_id,p_bau,v_tipo,abs(v_after-v_before),v_before,v_after,
    coalesce(v_nome,'Gerência'),'gerencia',auth.uid(),nullif(trim(coalesce(p_observacao,'')),'')
  );
  return v_after;
end
$fn$;

-- Entradas feitas por membro só podem aumentar o saldo do QG.
create or replace function public.mercado_membro_entrada(
  p_token text, p_item_id uuid, p_quantidade integer, p_observacao text default null
)
returns integer
language plpgsql
security definer
set search_path = public, auth, extensions, pg_temp
as $fn$
declare v_member record; v_before integer; v_after integer;
begin
  select * into v_member from public._mercado_sessao_membro(p_token);
  if v_member.acesso_id is null then raise exception 'Sessão inválida.' using errcode = '28000'; end if;
  if coalesce(p_quantidade,0)<=0 then raise exception 'A quantidade deve ser maior que zero.'; end if;

  select i.estoque_qg into v_before from public.mercado_itens i
    where i.id=p_item_id and i.ativo for update;
  if not found then raise exception 'Item não encontrado.'; end if;
  v_after:=v_before+p_quantidade;
  update public.mercado_itens set estoque_qg=v_after where id=p_item_id;

  insert into public.mercado_movimentos_baus(
    item_id,bau,tipo,quantidade,estoque_anterior,estoque_posterior,
    responsavel_nome,responsavel_tipo,responsavel_acesso_id,observacao
  )
  values(p_item_id,'qg','entrada',p_quantidade,v_before,v_after,
    v_member.nome,'membro',v_member.acesso_id,nullif(trim(coalesce(p_observacao,'')),'')); 
  return v_after;
end
$fn$;

-- Retirada de membros e gerência sempre baixa apenas do QG.
drop function if exists public.mercado_retirar_item(text, uuid, numeric);
create or replace function public.mercado_retirar_item(p_token text, p_item_id uuid, p_quantidade integer)
returns integer
language plpgsql
security definer
set search_path = public, auth, extensions, pg_temp
as $fn$
declare v_member record; v_before integer; v_after integer; v_nome text; v_tipo text; v_auth uuid; v_acesso uuid;
begin
  if auth.uid() is not null and coalesce(public.cuba_access_ok(),false) then
    select p.nome into v_nome from public.profiles p where p.user_id=auth.uid();
    v_tipo:='gerencia'; v_auth:=auth.uid();
  else
    select * into v_member from public._mercado_sessao_membro(p_token);
    if v_member.acesso_id is null then raise exception 'Sessão inválida.' using errcode = '28000'; end if;
    v_nome:=v_member.nome; v_tipo:='membro'; v_acesso:=v_member.acesso_id;
  end if;

  if coalesce(p_quantidade,0)<=0 then raise exception 'A quantidade deve ser maior que zero.'; end if;
  select i.estoque_qg into v_before from public.mercado_itens i
    where i.id=p_item_id and i.ativo for update;
  if not found then raise exception 'Item não encontrado.'; end if;
  if v_before<p_quantidade then raise exception 'Estoque insuficiente no QG. Disponível: %',v_before; end if;
  v_after:=v_before-p_quantidade;
  update public.mercado_itens set estoque_qg=v_after where id=p_item_id;

  insert into public.mercado_movimentos_baus(
    item_id,bau,tipo,quantidade,estoque_anterior,estoque_posterior,
    responsavel_nome,responsavel_tipo,responsavel_auth_id,responsavel_acesso_id
  )
  values(p_item_id,'qg','saida',p_quantidade,v_before,v_after,
    v_nome,v_tipo,v_auth,v_acesso);
  return v_after;
end
$fn$;

-- Histórico detalhado dos dois baús, restrito à gerência.
drop function if exists public.mercado_admin_listar_movimentos_baus(integer);
create function public.mercado_admin_listar_movimentos_baus(p_limite integer default 200)
returns table(
  id bigint, created_at timestamptz, item_nome text, bau text, tipo text,
  quantidade integer, responsavel_nome text, estoque_anterior integer,
  estoque_posterior integer, observacao text
)
language plpgsql
security definer
set search_path = public, auth, extensions, pg_temp
as $fn$
begin
  perform public._mercado_exigir_gerencia();
  return query
    select m.id,m.created_at,i.nome,m.bau,m.tipo,m.quantidade,m.responsavel_nome,
      m.estoque_anterior,m.estoque_posterior,m.observacao
    from public.mercado_movimentos_baus m
    join public.mercado_itens i on i.id=m.item_id
    order by m.created_at desc
    limit greatest(1,least(coalesce(p_limite,200),1000));
end
$fn$;

-- Remove qualquer sobrecarga numérica antiga que torne a chamada do membro ambígua.
drop function if exists public.mercado_membro_entrada(text, uuid, numeric, text);

revoke all on function public._mercado_sync_estoque_qg_legacy() from public, anon, authenticated;
revoke all on function public.mercado_admin_listar_itens_baus() from public, anon, authenticated;
revoke all on function public.mercado_admin_criar_item_baus(text,text,integer,integer) from public, anon, authenticated;
revoke all on function public.mercado_admin_atualizar_bau(uuid,text,text,integer,text) from public, anon, authenticated;
revoke all on function public.mercado_admin_listar_movimentos_baus(integer) from public, anon, authenticated;

grant execute on function public.mercado_admin_listar_itens_baus() to authenticated;
grant execute on function public.mercado_admin_criar_item_baus(text,text,integer,integer) to authenticated;
grant execute on function public.mercado_admin_atualizar_bau(uuid,text,text,integer,text) to authenticated;
grant execute on function public.mercado_admin_listar_movimentos_baus(integer) to authenticated;

grant execute on function public.mercado_listar_itens(text) to anon, authenticated;
grant execute on function public.mercado_membro_entrada(text,uuid,integer,text) to anon, authenticated;
grant execute on function public.mercado_retirar_item(text,uuid,integer) to anon, authenticated;

notify pgrst, 'reload schema';
commit;
