const autorizados={"3133":{nome:"Pablo Alves",foto:"images/pablo.jpg"},"3142":{nome:"Felipe Alves",foto:"images/felipe.jpg"}};const FORMSPREE_ENDPOINT="https://formspree.io/f/mqerwenp";
const accessPanel=document.getElementById("accessPanel"),confirmPanel=document.getElementById("confirmPanel"),invitePanel=document.getElementById("invitePanel"),finalPanel=document.getElementById("finalPanel"),passportForm=document.getElementById("passportForm"),passportInput=document.getElementById("passport"),accessMessage=document.getElementById("accessMessage"),identityPhoto=document.getElementById("identityPhoto"),identityName=document.getElementById("identityName"),identityPassport=document.getElementById("identityPassport"),inviteName=document.getElementById("inviteName"),soundToggle=document.getElementById("soundToggle"),flash=document.getElementById("flash"),hackAudio=document.getElementById("hackAudio"),systemAudio=document.getElementById("systemAudio"),voiceAudio=document.getElementById("voiceAudio"),suspenseAudio=document.getElementById("suspenseAudio");
hackAudio.volume=.55;systemAudio.volume=.7;voiceAudio.volume=.9;suspenseAudio.volume=.28;
let pessoaAtual=null,passaporteAtual=null,registroAtual=null,mutado=false,respostaEnviada=false;
function mostrarPainel(p){[accessPanel,confirmPanel,invitePanel,finalPanel].forEach(x=>x.classList.add("hidden"));p.classList.remove("hidden")}
function tocar(a){if(mutado)return Promise.resolve();a.currentTime=0;return a.play().catch(()=>{})}
function efeitoHacker(d=1500){document.body.classList.remove("hacking");void document.body.offsetWidth;document.body.classList.add("hacking");flash.classList.add("on");setTimeout(()=>flash.classList.remove("on"),80);setTimeout(()=>document.body.classList.remove("hacking"),d)}
function esperarFim(a,l=6000){return new Promise(r=>{let f=false;const c=()=>{if(f)return;f=true;a.removeEventListener("ended",c);r()};a.addEventListener("ended",c,{once:true});setTimeout(c,l)})}
async function registrarResposta(resposta){if(respostaEnviada)return true;const dados={nome:pessoaAtual,passaporte:passaporteAtual,resposta,convite:"Família Cuba",data_hora:new Date().toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})};try{const retorno=await fetch(FORMSPREE_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify(dados)});if(!retorno.ok)throw new Error("Falha");respostaEnviada=true;return true}catch(e){console.error(e);return false}}
passportInput.addEventListener("input",()=>passportInput.value=passportInput.value.replace(/\D/g,""));
passportForm.addEventListener("submit",async e=>{e.preventDefault();const p=passportInput.value.trim(),r=autorizados[p];accessMessage.className="message";if(!r){accessMessage.textContent="ACESSO NEGADO — passaporte não autorizado.";accessMessage.classList.add("error");efeitoHacker(700);tocar(hackAudio);return}registroAtual=r;pessoaAtual=r.nome;passaporteAtual=p;respostaEnviada=false;accessMessage.textContent="Passaporte localizado. Descriptografando identidade...";accessMessage.classList.add("success");efeitoHacker(1600);await tocar(hackAudio);setTimeout(()=>{identityPhoto.src=registroAtual.foto;identityName.textContent=pessoaAtual;identityPassport.textContent=`PASSAPORTE: ${passaporteAtual}`;mostrarPainel(confirmPanel)},1500)});
document.getElementById("confirmIdentity").addEventListener("click",async()=>{const b=document.getElementById("confirmIdentity");b.disabled=true;b.textContent="AUTORIZANDO...";efeitoHacker(1200);await tocar(systemAudio);await esperarFim(systemAudio,4000);await tocar(voiceAudio);await esperarFim(voiceAudio,5000);suspenseAudio.currentTime=0;if(!mutado)suspenseAudio.play().catch(()=>{});inviteName.textContent=pessoaAtual;mostrarPainel(invitePanel);b.disabled=false;b.textContent="SIM, SOU EU"});
document.getElementById("rejectIdentity").addEventListener("click",()=>{pessoaAtual=null;passaporteAtual=null;registroAtual=null;passportInput.value="";accessMessage.textContent="";mostrarPainel(accessPanel);passportInput.focus()});
document.getElementById("acceptInvite").addEventListener("click",async e=>{const b=e.currentTarget;b.disabled=true;b.textContent="REGISTRANDO RESPOSTA...";if(!await registrarResposta("ACEITOU")){b.disabled=false;b.textContent="ACEITAR O CONVITE";alert("Não foi possível registrar sua resposta.");return}document.getElementById("finalEyebrow").textContent="RESPOSTA REGISTRADA";document.getElementById("finalTitle").textContent=`BEM-VINDO À FAMÍLIA, ${pessoaAtual.toUpperCase()}`;document.getElementById("finalMessage").textContent="Sua escolha foi registrada. A partir de agora, sua história passa a fazer parte da Família Cuba.";mostrarPainel(finalPanel)});
document.getElementById("declineInvite").addEventListener("click",async e=>{const b=e.currentTarget;b.disabled=true;b.textContent="REGISTRANDO RESPOSTA...";if(!await registrarResposta("RECUSOU")){b.disabled=false;b.textContent="RECUSAR O CONVITE";alert("Não foi possível registrar sua resposta.");return}document.getElementById("finalEyebrow").textContent="RESPOSTA REGISTRADA";document.getElementById("finalTitle").textContent="CONVITE RECUSADO";document.getElementById("finalMessage").textContent="A Família Cuba respeita sua decisão. Este acesso será encerrado.";mostrarPainel(finalPanel)});
soundToggle.addEventListener("click",()=>{mutado=!mutado;[hackAudio,systemAudio,voiceAudio,suspenseAudio].forEach(a=>a.muted=mutado);if(mutado){suspenseAudio.pause();soundToggle.textContent="🔇"}else{if(!invitePanel.classList.contains("hidden")||!finalPanel.classList.contains("hidden"))suspenseAudio.play().catch(()=>{});soundToggle.textContent="🔊"}});